on:
  push:
    branches:
      - f24
  pull_request:
    branches:
      - f24
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  checks: write  # for coverallsapp/github-action to create new checks
  contents: read  # for actions/checkout to fetch code

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: 'production'
      
    services:
      redis:
        image: 'redis:7.2.4'
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4

      - name: Install PIP
        run: python -m pip install --upgrade pip
      
      - name: Install virtualenv
        run: pip install virtualenv

      - name: create virtualenv
        run: virtualenv .app
      
      - name: activate virtualenv
        run: source .app/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest